# Generated by Django 5.0.4 on 2024-07-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_designer',
            field=models.BooleanField(default=False, verbose_name='Is Designer'),
        ),
    ]
