# Generated by Django 5.0.4 on 2024-07-01 19:39

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount_percent', models.PositiveSmallIntegerField(verbose_name='Discount Percent')),
                ('coupon_type', models.CharField(choices=[('One Time', 'One Time'), ('With Time', 'With Time'), ('Permanent', 'Permanent')], max_length=20)),
                ('coupon_validity_time', models.TimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_note', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note')),
                ('total', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(default=orders.models.generate_random_string, editable=False, max_length=11, unique=True, verbose_name='Order Code')),
                ('status', models.CharField(choices=[('OnPay', 'On Pay'), ('New', 'New'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('OnShipping', 'On Shipping'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Referred', 'Referred')], default='OnPay', max_length=20, verbose_name='Order Status')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.coupon')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard', verbose_name='User Info')),
                ('products', models.ManyToManyField(to='products.productvariation', verbose_name='Order Items')),
            ],
        ),
    ]
