# Generated by Django 5.0.4 on 2024-08-05 20:43

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '__first__'),
        ('coupons', '0001_initial'),
        ('dashboard', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_note', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note')),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('total_price_with_discount', models.PositiveIntegerField(default=0)),
                ('total_price_with_coupon', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(default=orders.models.generate_random_string, editable=False, max_length=11, unique=True, verbose_name='Order Code')),
                ('status', models.CharField(choices=[('OnPay', 'On Pay'), ('New', 'New'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('OnShipping', 'On Shipping'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Referred', 'Referred')], default='OnPay', max_length=20, verbose_name='Order Status')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cart', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.cart', verbose_name='Order Items')),
                ('coupon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='coupons.coupon')),
                ('dashboard', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard', verbose_name='User Info')),
            ],
        ),
    ]
