# Generated by Django 5.0.4 on 2024-07-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_id_alter_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_ids',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product IDs'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
