# Generated by Django 5.0.4 on 2024-07-15 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0004_order_product_ids_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_ids',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.cart', verbose_name='Cart Items'),
        ),
    ]
