# Generated by Django 5.0.4 on 2024-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0005_remove_order_product_ids_remove_order_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(related_name='order', to='cart.cart', verbose_name='Order Items'),
        ),
    ]
