# Generated by Django 5.0.4 on 2024-07-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_product_cart_product'),
        ('orders', '0007_remove_order_cart_items_order_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.cart', verbose_name='Order Items'),
        ),
    ]
