# Generated by Django 5.0.4 on 2024-07-15 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_product_remove_cart_quantity_and_more'),
        ('orders', '0008_remove_order_cart_items_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.cart', verbose_name='Order Items'),
        ),
    ]
