# Generated by Django 5.0.4 on 2024-07-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_cart_items_cart_product_cart_quantity'),
        ('dashboard', '0001_initial'),
        ('orders', '0009_alter_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.cart', verbose_name='Order Items'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dashboard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard', verbose_name='User Info'),
        ),
    ]
