# Generated by Django 5.0.4 on 2024-07-14 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='Product Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.images', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='color',
            field=models.ManyToManyField(blank=True, to='products.color', verbose_name='Product Colors'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='features',
            field=models.ManyToManyField(blank=True, to='products.productfeature', verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='products.images', verbose_name='Product Images'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.ManyToManyField(blank=True, to='products.size', verbose_name='Product_sizes'),
        ),
    ]
