# Generated by Django 5.0.4 on 2024-07-15 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='applied_coupon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.coupon', verbose_name='اعمال کوپون'),
        ),
    ]
