# Generated by Django 5.0.4 on 2024-07-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariation_applied_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='applied_coupon',
        ),
    ]
