# Generated by Django 5.0.4 on 2024-07-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_ipaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
