# Generated by Django 5.0.4 on 2024-07-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0004_remove_productvariation_applied_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(related_name='products', to='products.productvariation', verbose_name='Cart Items'),
        ),
    ]
