# Generated by Django 5.0.4 on 2024-07-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_product_cart_product'),
        ('products', '0004_remove_productvariation_applied_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(related_name='carts', to='products.productvariation', verbose_name='Cart Items'),
        ),
    ]
