# Generated by Django 5.0.4 on 2024-07-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_product_remove_cart_quantity_and_more'),
        ('products', '0004_remove_productvariation_applied_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.productvariation', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
