# Generated by Django 5.0.4 on 2024-07-15 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_cart_items_cart_product_cart_quantity'),
        ('orders', '0010_alter_order_cart_alter_order_coupon_and_more'),
        ('products', '0004_remove_productvariation_applied_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(default=None, to='products.productvariation', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.coupon'),
        ),
    ]
