# Generated by Django 5.0.4 on 2024-07-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cart_cart_items_remove_cart_quantity_cartitem'),
        ('products', '0004_remove_productvariation_applied_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(default=None, to='products.productvariation', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
