# Generated by Django 5.0.4 on 2024-07-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_cart_cart_items_remove_cart_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
