# Generated by Django 5.0.4 on 2024-07-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cartitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
