# Generated by Django 5.0.4 on 2024-07-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_cart_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_active',
        ),
    ]
