# Generated by Django 5.0.4 on 2024-04-16 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='address',
            field=models.CharField(default='address', max_length=300, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='first_name',
            field=models.CharField(default='arsalan', max_length=50, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='last_name',
            field=models.CharField(default='payandeh', max_length=50, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='postalcode',
            field=models.CharField(default='123456', max_length=20, verbose_name='Postal Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='state',
            field=models.CharField(default='mashhad', max_length=30, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
