# Generated by Django 5.0.4 on 2024-07-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_ticket_priority_remove_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
    ]
