# Generated by Django 5.0.4 on 2024-07-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_ticket_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='ticket',
        ),
    ]
